### ISSUE TITLE
Missing "terminfo database" ?

### ISSUE THREAD

**Issue by fwn0** [henry-hsieh/tmux.appimage#2]
artix:/home/artix/Downloads/Tmux-x86_64.AppImage 
can't find terminfo database
&
artix:/home/artix/Downloads/Tmux-x86_64/usr/bin  /home/artix/Downloads/Tmux-x86_64/AppRun 
can't find terminfo database

**Comment by henry-hsieh** [comment]
Please download again, I added terminfo into the AppImage.

**Comment by fwn0** [comment]
thank you, it does work well now :)
